# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0002_places_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='checkins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
