# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0003_places_checkins'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='herenow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
