# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0004_places_herenow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('herenow', models.IntegerField(blank=True, null=True)),
                ('checkins', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='category',
            field=models.CharField(default='unverified', max_length=250),
        ),
    ]
