# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0005_auto_20161102_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
