# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0007_auto_20161102_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
