# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0010_auto_20161103_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
