# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0012_auto_20161103_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.DateTimeField(default=datetime.date(2016, 11, 3)),
        ),
    ]
