# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0014_auto_20161103_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.DateField(),
        ),
    ]
