# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0015_auto_20161103_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='formatted_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
