# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0019_auto_20161106_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
